### ISSUE TITLE
How to configure in Docker?

### ISSUE THREAD

**Issue by MatthK** [nymanjens/facto#4]
I managed to get the docker compose up and running and I can login. I first failed to get it running on my Raspberry Pi 4, and I also failed to point the DB to an existing MySql container. But when I eventually tried your vanilla setup, it worked at first try.

One other little issue I found is that I couldn't set the APPLICATION_SECRET with the normal user, and start the docker with `sudo docker-compose up -d`. But that's not a real issue.

But now I am trying to configure the app and setup some categories and accounts, but I can't find the conf directory. How can I map that volume to a local directory?

Also, how can I change the EUR sign into a $?

**Comment by nymanjens** [comment]
> I managed to get the docker compose up and running and I can login. I first failed to get it running on my Raspberry Pi 4, and I also failed to point the DB to an existing MySql container. But when I eventually tried your vanilla setup, it worked at first try.

Hmm, thanks for letting me know. I never use the Docker way myself, and I'm a bit of a Docker novice anyway, which probably explains why it may be a bit rough using it. I'm happy to accept pull requests if you have a better way of configuring it. 

> But now I am trying to configure the app and setup some categories and accounts, but I can't find the conf directory. How can I map that volume to a local directory?

I guess that's a flaw in `docker-compose.yml` that it doesn't map the conf folder to a local folder. You probably have to do that.

For the vanilla setup, it's easy: You just edit `conf/accounting-config.yml`

> Also, how can I change the EUR sign into a $?

You'll have to change this field in [Currency.scala#L27](https://github.com/nymanjens/facto/blob/master/app/shared/src/main/scala/app/common/money/Currency.scala#L27)

And then you'll have to (unfortunately) compile the whole thing. You need the scala builder (sbt) and node.js for this. In case you want to use Docker for that, here is a Dockerfile for compiling another project of mine that works with the same framework: https://github.com/nymanjens/quizmaster/blob/master/Dockerfile
(I think it should translate exactly to facto)

**Comment by MatthK** [comment]
I did make some progress, but still failed in the end.

I managed to get the conf directory mapped in the docker-compose. And I also made a change to the Database volume, so basically all the data would be in one place.

However, I couldn't make basic changes to the `accounting-config.yml` to adjust some categories or accounts, and mostly replace the users Alice and Bob with my wife and myself. Whenever I replace Alice and Bob with two other names, I keep getting a console error saying that `No user exists with loginName 'matth'`. But I have defined such a user.

And I haven't even tried to get to the compiling yet. I fear I will give up and look for another solution. 

In case somebody else is interested, this is the `docker-compose.yml` that is working.

```
version: "3.3"

services:
  db:
    container_name: MariaDB
    image: mariadb:10.3
    volumes:
    - /facto_data/db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: facto
      MYSQL_DATABASE: facto

  web:
    container_name: Facto
    depends_on: [db]
    command: bin/server
    image: nymanjens/facto:latest
    ports: ["9000:9000"]
    restart: always
    environment:
      APPLICATION_SECRET: long_and_secret_string
      DATABASE_URL: jdbc:mysql://db:3306/facto?user=root&password=facto&disableMariaDbDriver
    volumes:
    - /facto/facto_data/conf:/app/conf
```

I also copied a bunch of files over from the `/app/conf` directory into my data directory, as those are not in the Git-files, but I found them in the docker container.

```
accounting-config.yml
application.conf
messages
messages.nl
routes
serviceWorker.template.js
```

The `application.conf` file has the following values:

```
# Secret key
# ~~~~~
play.http.secret.key = "long_and_secret_string"

# The application languages
# ~~~~~
play.i18n.langs = ["en"]

# MySQL database:
db.default.driver=com.mysql.jdbc.Driver
db.default.url="jdbc:mysql://db:3306/facto?user=root&password=facto&disableMariaDbDriver"
db.default.slick.profile = "slick.jdbc.MySQLProfile$"

app.setup.defaultPassword = "long_secret_password"
app.accounting.configYamlFilePath = "/app/conf/accounting-config.yml"
```
